services:
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - edge

  messaging:
    build: ./messaging
    restart: unless-stopped
    volumes:
      - messaging_data:/app/data
    networks:
      - edge

  gochecklist:
    build: ./gochecklist
    restart: unless-stopped
    environment:
      - MESSAGING_SERVICE_URL=http://messaging:7000
    volumes:
      - gochecklist_data:/app/data
    networks:
      - edge

  goweather:
    build: ./goweather
    restart: unless-stopped
    environment:
      - MESSAGING_SERVICE_URL=http://messaging:7000
    volumes:
      - goweather_data:/app/data
    networks:
      - edge

  gocalories:
    build: ./gocalories
    restart: unless-stopped
    volumes:
      - gocalories_data:/app/data
    networks:
      - edge

volumes:
  caddy_data:
  caddy_config:
  gochecklist_data:
  goweather_data:
  gocalories_data:
  messaging_data:

networks:
  edge:
